function [b,a] = butter_lowpass(N, Fc)
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 31-Jul-2016 13:16:44

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

% N  = Order
% Fc = Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
[b,a] = butter(N, Fc, 'low');

%h  = fdesign.lowpass('N,F3dB', N, Fc);
%Hd = design(h, 'butter');

% [EOF]
